Rename ego4d/internal/validation/types.py to ego4d/internal/validation/manifest.py
This will fix the following error - AttributeError: partially initialized module 're' has no attribute 'compile' (most likely due to a circular import)