Update requirements.txt (#292)
Summary:
The repository expects to have `pycocotools` installed but it's not part of the requirements:

```
ego4d/research/util/masks.py", line 6, in <module>
    from pycocotools import mask as mask_utils
ModuleNotFoundError: No module named 'pycocotools'
```

Happens if you run things like this:

```
from ego4d.research.readers import PyAvReader, TorchAudioStreamReader
from ego4d.research.util.masks import blend_mask, decode_mask
```

Pull Request resolved: https://github.com/facebookresearch/Ego4d/pull/292

Reviewed By: devanshk

Differential Revision: D52883314

Pulled By: miguelmartin75

fbshipit-source-id: 780bdc4120ae988e2d4baa0def8bea9972bd8f09