Update requirements.txt
The repository expects to have `pycocotools` installed but it's not part of the requirements:

```
ego4d/research/util/masks.py", line 6, in <module>
    from pycocotools import mask as mask_utils
ModuleNotFoundError: No module named 'pycocotools'
```

Happens if you run things like this:

```
from ego4d.research.readers import PyAvReader, TorchAudioStreamReader                                
from ego4d.research.util.masks import blend_mask, decode_mask 
```